// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzpevzvnejmshzfscyje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cGV2enZuZWptc2h6ZnNjeWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjUxODksImV4cCI6MjA3MTgwMTE4OX0.Ft0114sBl-v-FMrR6_wGi_oV3ZKMHnrHoYI-FXm-HSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});